# Generated by Django 2.1.1 on 2018-11-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('EmployeName', models.CharField(max_length=50)),
                ('LotNo', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=50)),
                ('WrongLocation', models.BooleanField(default=False)),
            ],
        ),
    ]
