# Generated by Django 2.1.4 on 2019-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepartmentLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentlog',
            name='AllowedDepts',
            field=models.CharField(blank=True, default='None', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='departmentlog',
            name='CorrectDept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
