# Generated by Django 2.1.4 on 2019-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepartmentLog', '0003_departmentlogusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentlog',
            name='DeptGlobalRank',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='departmentlog',
            name='Notes',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
