# Generated by Django 2.0.1 on 2018-07-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LABLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('LotNo', models.CharField(max_length=20)),
                ('Department', models.CharField(default='Q-LAB', max_length=20)),
                ('VisualNotClosed', models.BooleanField(default=False)),
            ],
        ),
    ]
