# Generated by Django 2.0.1 on 2018-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lablog',
            name='EmployeName',
            field=models.CharField(default='o', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lablog',
            name='LabNotFinished',
            field=models.BooleanField(default=False),
        ),
    ]
