# Generated by Django 2.1.4 on 2019-01-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABLog', '0002_auto_20180904_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='lablog',
            name='Notes',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
