# Generated by Django 2.1.4 on 2019-01-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABLog', '0003_lablog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lablog',
            name='OpNumOpen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
