# Generated by Django 2.1.4 on 2019-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABLog', '0004_lablog_opnumopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lablog',
            name='Notes',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
