# Generated by Django 2.1.4 on 2019-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countlog',
            name='QLabOpen',
            field=models.BooleanField(default=False, verbose_name='Q-Lab operation is probably open'),
        ),
    ]
