# Generated by Django 2.1.4 on 2019-02-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0002_countlog_qlabopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='countlog',
            name='Notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes'),
        ),
    ]
