# Generated by Django 2.1.4 on 2019-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0003_countlog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='countlog',
            name='OpSeqNum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operation Sequence Number'),
        ),
        migrations.AddField(
            model_name='countlog',
            name='OverrideQtys',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Override_QTY from Operation table selected?'),
        ),
    ]
