# Generated by Django 2.1.4 on 2019-02-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0004_auto_20190225_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countlog',
            name='OverrideQtys',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Override_QTY from Operation table selected?'),
        ),
    ]
