# Generated by Django 2.1.4 on 2019-03-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0005_auto_20190225_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='countlog',
            name='BelowTargetQty',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is the counted QTY < order target qty?'),
        ),
        migrations.AddField(
            model_name='countlog',
            name='DesiredQty',
            field=models.IntegerField(blank=True, null=True, verbose_name='WORK_ORDER.DESIRED_QTY:'),
        ),
    ]
