# Generated by Django 2.1.4 on 2019-04-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CountingLog', '0006_auto_20190312_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workOrder', models.CharField(max_length=20)),
                ('originalWorkOrder', models.CharField(blank=True, max_length=20, null=True)),
                ('opSequenceFrom', models.IntegerField()),
                ('opSequenceTo', models.IntegerField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('totalCount', models.IntegerField(blank=True, null=True)),
                ('dateCount1', models.DateTimeField(blank=True, null=True)),
                ('quantity1', models.IntegerField(blank=True, default=0, null=True)),
                ('sampleSize1', models.IntegerField(blank=True, default=0, null=True)),
                ('buyOffBadge1', models.IntegerField(blank=True, default=0, null=True)),
                ('buyOffPerson1', models.CharField(blank=True, max_length=150, null=True)),
                ('dateCount2', models.DateTimeField(blank=True, null=True)),
                ('quantity2', models.IntegerField(default=0)),
                ('sampleSize2', models.IntegerField(blank=True, default=0)),
                ('buyOffBadge2', models.IntegerField(blank=True, default=0)),
                ('buyOffPerson2', models.CharField(blank=True, max_length=150, null=True)),
                ('dateCount3', models.DateTimeField(blank=True, null=True)),
                ('quantity3', models.IntegerField(default=0)),
                ('sampleSize3', models.IntegerField(blank=True, default=0)),
                ('buyOffBadge3', models.IntegerField(blank=True, default=0)),
                ('buyOffPerson3', models.CharField(blank=True, max_length=150, null=True)),
                ('dateCount4', models.DateTimeField(blank=True, null=True)),
                ('quantity4', models.IntegerField(default=0)),
                ('sampleSize4', models.IntegerField(blank=True, default=0)),
                ('buyOffBadge4', models.IntegerField(blank=True, default=0)),
                ('buyOffPerson4', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
